version: "3"
services:
  sut:
    build: .
    volumes:
      - ./result:/work/result
      - ./test/spec:/work/spec/test:ro
      - ./test/steps:/work/spec/steps:ro
      - ./test/features:/work/spec/features:ro
    depends_on:
      - nginx
    command: rspec -r turnip/rspec
  nginx:
    image: nginx:alpine
